# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dv < Formula
  desc "A beautiful, snappy, and highly interactive tool for exploring diffs without leaving your terminal."
  homepage "https://github.com/darrenburns/dv"
  version "0.1.0-alpha.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darrenburns/dv/releases/download/v0.1.0-alpha.3/dv_0.1.0-alpha.3_darwin_amd64.tar.gz"
      sha256 "f15d37d1aec80d7f993fae23d6e3413b4ba77b7e483873767ae3115ce1022547"

      def install
        bin.install "dv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darrenburns/dv/releases/download/v0.1.0-alpha.3/dv_0.1.0-alpha.3_darwin_arm64.tar.gz"
      sha256 "7417f20f30e45e484bb3b0284edd0cd9cecb83b461cf3e71b2f2b69077d5594b"

      def install
        bin.install "dv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenburns/dv/releases/download/v0.1.0-alpha.3/dv_0.1.0-alpha.3_linux_amd64.tar.gz"
      sha256 "26133ea4c7f3039a0ead687076f4fdad2c08c31160b024323427a17fef28cbc2"
      def install
        bin.install "dv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenburns/dv/releases/download/v0.1.0-alpha.3/dv_0.1.0-alpha.3_linux_arm64.tar.gz"
      sha256 "e0ce57d73391550434bb8187ea4280568d60c4a1685852c77ad6a433f5fd1898"
      def install
        bin.install "dv"
      end
    end
  end
end
