# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dv < Formula
  desc "A beautiful, snappy, and highly interactive tool for exploring diffs without leaving your terminal."
  homepage "https://github.com/darrenburns/dv"
  version "0.5.0-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darrenburns/dv/releases/download/v0.5.0-beta.1/dv_0.5.0-beta.1_darwin_amd64.tar.gz"
      sha256 "b03fe6c36c113513e7ae06c99b4407f3d0d80f31b13837cdc9df1b6b97a2da74"

      define_method(:install) do
        bin.install "dv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darrenburns/dv/releases/download/v0.5.0-beta.1/dv_0.5.0-beta.1_darwin_arm64.tar.gz"
      sha256 "0e00df38ae1186377b76eeeb7eaf0ff95089ca5269e0396dae2c43550cf5fb26"

      define_method(:install) do
        bin.install "dv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenburns/dv/releases/download/v0.5.0-beta.1/dv_0.5.0-beta.1_linux_amd64.tar.gz"
      sha256 "9c7c137dc51aba7befe8ddf72aa1dfbec5d378733114dd271adbf20aa8b02bc7"
      define_method(:install) do
        bin.install "dv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenburns/dv/releases/download/v0.5.0-beta.1/dv_0.5.0-beta.1_linux_arm64.tar.gz"
      sha256 "23597460ec598242a7a7c300c25ee516a01edc97cf8f8400202bec85e9148a9c"
      define_method(:install) do
        bin.install "dv"
      end
    end
  end
end
